# Generated by Django 4.2.7 on 2024-01-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_post_review_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='post',
        ),
    ]
